name: App (project setup, running tests and linter)
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      
      - run: make setup 

      - name: running tests
        run: make test

      - name: running linter
        run: make lint
